### PR TITLE
Added tests for additional db operations

### PR DESCRIPTION
**Pull request by Du-z**
Struggled to get RPC Modify to work, it is currently failing with `error code -32602 (Invalid params)`.

I'm not to sure if I am using Modify correctly though.

### CODE REVIEW

**Comment by Du-z** [comment]
Remaining list of tests now includes.

- Multiple result set handing
- DB Error Responses
- Multithreaded testing

**Comment by ProphetLamb** [comment]
Thanks! Ill have a look at the failing tests later on.

**Comment by ProphetLamb** [comment]
Please note that modify uses [JSON Patch](https://jsonpatch.com/) syntax

**Comment by ProphetLamb** [comment]
Apparently there was a breaking change to PATCH vs CHANGE for the REST endpoint. Fixed it

**Review by ProphetLamb — APPROVED** [review]
Looking good! Thanks for the testcases!

**Pull request merged**
