### PR TITLE
Added tests for Stop, Start and Use

### PR DESCRIPTION
**Pull request by Du-z**
The Rest connection now throws when try to use it with unset credentials. This is to try and keep it consistent with RPC.

Also switched the round trip tests to use a static date time and commented them out due to them failing from the prepended `00` issue.

### CODE REVIEW

**Comment by Du-z** [comment]
Looks like nightly isn't keen with the connection being closed.

**Comment by Du-z** [comment]
@ProphetLamb is it possible to make the builds not cancel when one encounters an error?

Previously the nightlies would fail, and the standard builds would get canceled. It makes it hard to draw conclusions if it is an issue with the nightly build or all builds.

**Comment by ProphetLamb** [comment]
@Du-z addling `fail-fast: false` to the matrix solves this

**Review by ProphetLamb — APPROVED** [review]
Thanks for figuring the cancellation out, that's a huge help! <3

**Pull request merged**
