### PR TITLE
Compatibility with the nightly branch

### PR DESCRIPTION
**Pull request by ProphetLamb**
..., preferable without breaking the stable branch

### CODE REVIEW

**Comment by ProphetLamb** [comment]
Since it doesn't seem possible to trivially satisfy both stable and nightly branches, I see three options:
1. Separate /stable branch for lts
2. Separate /nightly branch for on the edge 
3. Drop nightly support entirely.

For 1 and 2 the `matrix.channel` will choose nightly versus stable depending on the branch, instead of both channels

**Comment by Du-z** [comment]
Could we drop the nightly tests for the master branch, and do nightly tests against a develop branch?

Stable tests against:
`master`: the is where the released and very soon to be released builds go.
`hotfix/*`: for the rare bug that must be fixed.

Nightly tests against:
`develop` most PRs merge into here
`feature/*`: most of our commits are done here, and will merge into develop via PRs

This way develop can merge into directly into master as soon as the next version of Surreal is released with tests that are already green.

The main downside is that it requires us to dev against a potentially buggy nightly. If there are release candidate builds of surreal, I could see this this strategy working very well.

**Comment by ProphetLamb** [comment]
@Du-z That sounds great! Ill restructure according to your suggestion. Thanks for the input!
On that note, before actually hacking together a solution, ill formalize these decision in a /CONTRIBUTING.md .
Feel free to review it at your leisure once created.

**Comment by ProphetLamb** [comment]
I have reverted all code-changes in this branch, so that we can now merge it.
Since affecting these changes will invalidate, I will change the following PRs to the develop branch.
- https://github.com/Surreal-Net/Surreal.Net/pull/75
- https://github.com/Surreal-Net/Surreal.Net/pull/64

**Review by Du-z — APPROVED** [review]
Looks good, I just updated README.md to be a bit more explicit about which branch to merge the PR into.

Also i think the latest release didn't go out properly? Looks like it used the wrong version number.

**Pull request merged**
