### PR TITLE
Added MemberData to query tests and fixed some failures (With a big caveat)

### PR DESCRIPTION
**Pull request by Du-z**
Downgraded xUnit from 2.4.0 to 2.4.2 to enable more tests #62
Added more test case, fixing issues as they come up.

**There is a big conflict though:-**
When I insert a object with a default value I would expect that I can query the DB with that default value and get back the object. But with `DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault` these default values are not saved into the DB and therefor cannot be queried.

Changing to `DefaultIgnoreCondition = JsonIgnoreCondition.Never` fixes this issue, but then the RPC Create starts to fail with the following error.
```
Code: -32000
Message: There was a problem with the database: The table does not exist.
```

I have found debugging the RPC connection quite tricky. Any thoughts on how to resolve this?

### CODE REVIEW

**Comment by ProphetLamb** [comment]
Thanks for the PR! I am looking into it. On that node, ill implement ILogger support, to allow for easier debugging. I agree that it can be quite difficult to find out what the RPC client is sending

**Comment by ProphetLamb** [comment]
The error relates to the signin process. Where a strong typed structure is used in order to authenticate. We set `Username` and `Password`, but the class contains more fields. When not ignoring null values the following request is made:

```csharp
{
  "id": "1Xh2D2i0",
  "method": "signin",
  "params": [
    { "ns": null, "db": null, "sc": null, "user": "root", "pass": "root" }
  ]
}

```

This is obviously invalid. For now, I'll remove the strong typed authentication structure. That should fix the specific issue, others of similar nature may occur

**Comment by ProphetLamb** [comment]
Fixed!

**Review by ProphetLamb — APPROVED** [review]
The test cases are looking good to me. Thought I think we are missing testcases for queries multiple results, we should have just about every type dependent scenario covered

**Comment by Du-z** [comment]
Cheers, my TODO list of tests now includes.

-     Change the Query tests to test all the DB operations not just queries.
-     Multiple result set handing
-     DB Error Responses

**Pull request merged**
